title: Hares Faiez
email: hares.faiez@gmail.com
phone: +216 26 87 17 88
description: >
    Programmign and design tales
about: >
    Programmer

avatar: "https://avatars3.githubusercontent.com/u/10279086?v=3&s=460"

url: "http://haresfaiez.github.io"
baseurl: ""
avatar: https://avatars3.githubusercontent.com/u/10279086?v=3&s=460

result: ""

twitter_handle  : hrsfaiez
behance_handle  : hrsfaiez
github_handle   : haresfaiez
goodreads_handle: 53209781-hares-faiez

markdown: kramdown
