#TODO:choose a better blog name, maybe smthng like 'the _ programmer'
title: Hares Faiez
email: hares.faiez@gmail.com
description: >
    Software engineering blog
about: >
    My name is Hares Faiez. I am a programmer and a designer.
    I share here my thoughts about software development.

baseurl: "" # the subpath of your site, e.g. /blog
url: "haresfaiez.github.io" # the base hostname & protocol for your site
twitter_username: hrsfaiez
behance_username: hrsfaiez
github_username:  haresfaiez

# Build settings
markdown: kramdown
