title: Faten Elhares
email: hares.faiez@gmail.com
phone: +216 26 87 17 88
description: >
    Faten Elhares personal web site

url: "https://fatenelhares.github.io"
baseurl: ""

result: ""

twitter_handle  : FatenElhares
github_handle   : FatenElhares

markdown: kramdown
