title: Hares Faiez
email: faiez.hrs@gmail.com
phone: +216 26 87 17 88
description: >
    Software engineering blog
about: >
    Hi! I am Hares Faiez. I am a programmer.
    I tell the stories of my small shiny discoveries and I share the thoughs of my journey.
    Currently,  I am looking for new opportunities.
    If you are looking for a passionate team player to join your team, please get in touch.

avatar: "https://avatars3.githubusercontent.com/u/10279086?v=3&s=460"

url: "http://haresfaiez.github.io"
baseurl: ""
twitter_username: hrsfaiez
behance_username: hrsfaiez
github_username:  haresfaiez

# Build settings
markdown: kramdown
