#TODO:choose a better blog name, maybe smthng like 'the _ programmer'
title: Hares Faiez
email: hares.faiez@gmail.com
description: > #TODO:write some description about yourself here
baseurl: "" # the subpath of your site, e.g. /blog
url: "haresfaiez.github.io" # the base hostname & protocol for your site
twitter_username: hrsfaiez
github_username:  haresfaiez

# Build settings
markdown: kramdown
