#TODO:choose a better blog name, maybe smthng like 'the _ programmer'
title: Hares Faiez
email: hares.faiez@gmail.com
description: >
    Software engineering blog
about: >
    Hi!
    I am Hares Faiez.
    I am a programmer.
    I write here about what I have learned and what I am trying to learn.
    It is mostly about software development and product design.

baseurl: "" # the subpath of your site, e.g. /blog
url: "haresfaiez.github.io" # the base hostname & protocol for your site
twitter_username: hrsfaiez
github_username:  haresfaiez

# Build settings
markdown: kramdown
