#TODO:choose a better blog name, maybe smthng like 'the _ programmer'
title: Hares Faiez
email: hares.faiez@gmail.com
description: >
    Hi!
    I am Hares Faiez.
    I am a Software engineering student.
    I write about all those thoughts that blow my mind about software development.
    I would appreciate if you give your opinion about them.
    Have a great day.

baseurl: "" # the subpath of your site, e.g. /blog
url: "haresfaiez.github.io" # the base hostname & protocol for your site
twitter_username: hrsfaiez
github_username:  haresfaiez

# Build settings
markdown: kramdown
