title: Hares Faiez
email: faiez.hrs@gmail.com
phone: +216 26 87 17 88
description: >
    Programmign and design tales
about: >
    Hi! I am Hares Faiez. I program and design software.
    I tell the stories of my little discoveries and I share thoughs from my journey.
    I will be happy to learn about your opinions and your experiences with what I write about.

avatar: "https://avatars3.githubusercontent.com/u/10279086?v=3&s=460"

url: "http://haresfaiez.github.io"
baseurl: ""
avatar: https://avatars3.githubusercontent.com/u/10279086?v=3&s=460
twitter_handle  : hrsfaiez
behance_handle  : hrsfaiez
github_handle   : haresfaiez
goodreads_handle: 53209781-hares-faiez

markdown: kramdown
